### ISSUE TITLE
Support multiple evaluation tasks

### ISSUE THREAD

**Issue by ahumenberger** [symflower/eval-dev-quality#165]
As of now, we only have a single evaluation task, that is, "provide tests for this code". In a future release we want to run other tasks as well, like "repair this compilation error". For this, we need structural changes.

**Tasks:**
- [x] Introduce string enum `TaskIdentifier`
- [x] Change `Model` interface such that it has a `RunTask(TaskIdentifier,...)` method
  - [x] Remove `GenerateTestsForFile` from `Model` interface as this becomes a task
- [x] Add a method `IsTaskSupported(TaskIdentifier)` to the `Model` interface to let models specify if they support a specific task.
- [x] Introduce proper `Repository` type
  - [x] Each repository can allow/disallow certain tasks
    - [x] This should not be hardcoded. Therefore a `repository.json` file can be created in the repository's root directory. If no such file exists, all tasks are allowed.
- [x] Create `Task` interface and suitable implementations
