### ISSUE TITLE
Dump the assessments in the CSV files once they happen and not in the end of all executions

### ISSUE THREAD

**Issue by ruiAzevedo19** [symflower/eval-dev-quality#237]
## TODO 

**1st iteration**
- [x] Dump the assessments into the `evaluation.csv`  every time a task is executed

**2nd iteration**
- [x] Create the other CSVs from the `evaluation.csv`
  - read `evaluation.csv` > sum the results > write to file
  - [x] `models-summed.csv`
  - [x] `<language>-summed.csv` 

### Follow-ups
- [x] Store the tasks and repositories in the evaluation records  
  - https://github.com/symflower/eval-dev-quality/pull/241#discussion_r1666425640
- [ ] Add the model human-readable name and its costs only when the raw records of the `evaluation.csv` are processed 
  - https://github.com/symflower/eval-dev-quality/pull/241#discussion_r1666436342
- [x] Change `EvaluationRecordsPerModel` to be `map[string][]*metrics.Assessments`
  - https://github.com/symflower/eval-dev-quality/pull/241#discussion_r1668526526

**Comment by bauersimon** [comment]
- would basically just have only one `evaluation.csv` where everything is just dumped on the fly
- the other two csvs can be created from the first one, it should just be different summing
  - thats also already the first step towards "combining multiple evaluations"
  - basically one single "raw" results file, and then we can do all the pretty stuff in a separate step
- basically in this iteration you just read in the raw csv and do the summing up and write it out separately

**Comment by bauersimon** [comment]
remaining task will be implemented with https://github.com/symflower/eval-dev-quality/issues/296
