### ISSUE TITLE
Check if all testdata repositories are well-formed just once, and not in every task run

### ISSUE THREAD

**Issue by ruiAzevedo19** [symflower/eval-dev-quality#263]
Goal: check if the testdata repositories are well-formed just once and not in every run.

Currently, we check if a task repository is well-formed when we run the task itself. Since we can have multiple runs, we are checking the same thing over and over again. There needs to be an extra step before running all the tasks where we validate the testdata repositories.

#### TODO

- [x] add a new method to the repository interface `Validate() error` 
- [x] each task file contains a validation function that knows how to validate the repository 
  - [x] write-tests task
  - [x] code-repair task
  - [x] transpilation task 
- [x] the repository validation needs to happen in 2 places in `evaluate/evaluate.go:Evaluate`
  - [x] when we run the evaluation for the `plain` repository (after calculating the `temporaryRepositories` and before the evaluation loop)
  - [x] when we run the evaluation for all repositories  (after calculating the `temporaryRepositories` and before the evaluation loop)

**Comment by bauersimon** [comment]
Would basically just extend the 

```go
type Repository interface { 
	Validate() error
...
```

and that way you can just call that function in the two locations you mentioned above right after creating the repository

and internally you will probably do a switch based on the task identifiers that the repository has... and do one special validation function per task... would probably even leave the validation logic itself where the tasks are (i.e. `task-write-test.go`)  that way the validation for a task is still where the task happens

**Comment by bauersimon** [comment]
so basically i would not do a function that knows how to validate all types of repository... I think it is still good that this logic is separated... but the way that the repository validation is invoked should just be via the `Repository` interface and only once when the repository is created
