### ISSUE TITLE
Pull ollama models

### ISSUE THREAD

**Issue by Munsio** [symflower/eval-dev-quality#283]
We want to pull ollama models if they are not available, this will allow us to run ollama models inside containerized evaluations.

### Tasks:
- [ ] Check if the requested ollama model is locally available
- [ ] Check if the requested ollama model is publicly available
- [ ] Pull the ollama model
