### ISSUE TITLE
Data visualization based on evaluation CSV files

### ISSUE THREAD

**Issue by ruiAzevedo19** [symflower/eval-dev-quality#296]
Goal: create a HTML report with graphs for data visualization. 
Tool: [D3.js](https://d3js.org/) library for data visualization graphs

#### TODO

- [x] Create a table for the evaluation CSV file
- [ ] Scatter plot
  - [x] Create a CSV file that stores the models meta information such as pricing and human-readable names
     - [x] Extend the model's interface with a `MetaInformation` function that returns a model's meta information
     - [x] Write the meta information in a CSV file
  - [ ] Create a scatter plot with the model costs and score 

- [ ] error bars over multiple runs, to show variance

**Comment by bauersimon** [comment]
developed internally
