### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#301]
# Highlights :star2: 

- Spring Boot :leafy_green: unit test support: evaluating how models generate tests for Spring
- Code Migration :repeat: task: asking models to migrate i.e. tests from JUnit 4 to JUnit 5

# Changes :bulb:  

- [x] Development & Management 🛠️
  - [x] Linters in development environment and CI #18 #355 #359 #377 @zimmski 
  - [x] Bump golang.org/x/image from 0.11.0 to 0.18.0 #340 #@dependabot
  - [x] VSCode recommended extensions and debugging configuration #361 @bauersimon 
  - [x] Enable Symflower linter by default in VSC #362 @ruiAzevedo19 
  - [x] Script for tagging and releasing #344 #391 @bauersimon 
  - [x] Add Symflower License in GitHub Actions so the CI works again #389 #393 @zimmski 
  - [x] Clean up old container images #394 #395 @zimmski
  - [x] Tag container images of releases #396 @zimmski
- [x] Documentation 📚
  - [x] Add issue templates for bug and feature requests #338 #342 #345 #346 @bauersimon 
  - [x] Improve wording of templates and documentation #343 @bauersimon 
  - [x] Update symflower.com with DevQualityEval entries #339 #348 @zimmski 
  - [x] Roadmap issue template clarification on workflow and payment page #388 @bauersimon 
  - [x] Roadmap issue template clarification on how to use the roadmap issue itself to create release notes #397
- [x] Evaluation ⏱️
  - [x] refactor, Clarify wording, logs, debugging regarding symflower fix #352 @bauersimon 
  - [x] refactor, Simplify assessment cleanup for tests #353 @ruiAzevedo19 
  - [x] Cleanup logging and log to JSON for easier parsing #379 @bauersimon 
  - [x] fix, Solving Plain once (with or without template) is enough to not get disqualified #360 @bauersimon 
- [x] Models 🤖
  - none
- [x] Reports & Metrics 🗒️
  - [x] Write run count to CSV report #337 @bauersimon  
  - [x] Remove category SVG from the report, because we are moving to a leaderboard #356 @zimmski 
  - [x] Remove categorization and total score of reporting, and the "report" command #357 @zimmski 
  - [x] Remove scoring from within the evaluation and remove and lint unused functions #369 @bauersimon 
  - [x] Remove assessment collection #378 @bauersimon 
  - [x] Max scores per case in repository #390 #392  @bauersimon 
- [x] Operating Systems 🖥️
  - none
- [x] Tools 🧰
  - [x] Script to convert all SVG files to PNG with Inkscape #349 @bauersimon 
  - [x] Script to find max coverage score from result data #380 @bauersimon 
- [x] Tasks 🔢
  - [x] "Write-test" task with Symflower Smart Test Template as base #350 #351 #354 #358 @bauersimon 
  - [x] Spring Boot "write-test" #365 #367 @bauersimon 
  - [x] Migration from JUnit4 to JUnit5 #375 #376 @ruiAzevedo19 

# Details :mag: 

- [x] Take details from automatic release description of GitHub.

Tasks of this 

> ❓ When should a release happen? Check the [`README`](../../README.md#when-and-how-to-release)!

- [x] Do a full evaluation with the version
  - [x] Exclude certain Openrouter models by default
    - [x] `nitro` cause they are just faster
    - [x] `extended` cause longer context windows don't matter for our tasks
    - [x] `free` and `auto` cause these are just "aliases" for existing models
  - [x] Exclude special-purpose models
    - [x] Vision models
    - [x] Roleplay and creative writing models
    - [x] Classification models
    - [x] Models with internet access (usually denoted by `-online` suffix)
    - [x] Models with extended context windows (usually denoted by `-1234K` suffix)
  - [x] Always prefer fine tuned (`-instruct`, `-chat`) models over a plain base model
- [x] Tag version (tag can be moved in case important merges happen afterwards)
- [x] For all issues of the current milestone, one by one, add them to the roadmap tasks (it is ok if a task has multiple issues) with the users that worked on it
  - Fixed bugs should always be sorted into respective relevant categories and not in a generic "Bugs" category!
- [x] For all PRs of the current milestone, one by one, add them to the roadmap tasks (it is ok if a task has multiple issues) with the users that worked on it
  - Fixed bugs should always be sorted into respective relevant categories and not in a generic "Bugs" category!
- [x] Search all issues for ...
  - [x] Unassigned issues that are closed, and assign them someone
  - [x] Issues without a milestone, and assign them a milestone
  - [x] Issues without a label, and assign them at least one label
- [x] Write the release notes @ https://github.com/symflower/eval-dev-quality/releases
  - [x] Use the tasks that are already there for the release note outline
  - [x] Add highlighted features based on the done tasks, sort by how many users would use the feature
- [x] Do the release
  - [x] With release notes
  - [x] Set as latest release
- [x] Prepare the next roadmap
  - [x] Create a milestone for the next release
  - [x] Create a new roadmap issue for the next release
    - [x] Move all open tasks/TODOs from this roadmap issue to the next roadmap issue.
    - [x] Move every comment of this roadmap issue as a TODO to the next roadmap issue. Mark when done with a :rocket: emoji.
- [x] Blog post containing evaluation results, new features and learnings
  - [x] Copy the template: `doc/devqualityeval/template-deep-dive.md` in the company `symflower.com` repository
  - [x] Write out the blog post content as described in the template
  - [x] Update README with blog post link and new header image
  - [x] Update repository link with blog post link
  - [x] https://github.com/symflower/eval-dev-quality/discussions
    - [x] Remove the previous announcements
    - [x] Add a "Deep dive: $blog-post-title" announcement for the blog post, unpin all others and pin this one
    - [x] Add a "v$version: $summary-of-highlights" announcement for the release, unpin all others and pin this one
  -   [x] symflower.com
      -   [x] Update "latest DevQualityEval deep dive" mentions
      -   [x] Update DevQualityEval blog series lists with new entries
      -   [x] Update LLM blog series lists with new entries
   - [x] Update payment process for supporting DevQualityEval
      - [x] New Stripe payment link for this version
      - [x] Update payment logic with new Google Drive folder of the evaluation
      - [x] Update Payment link in this README
      - [x] Update Payment link on symflower.com (except for the one deep dive that mentions exactly these results)
    - [x] Create an issue in the company tracker for Markus to announce the new deep dive on Twitter and LinkedIn
-   [x] Close this issue
-   [x] Close the current milestone
-   [x] Announce release
-   [x] Eat cake 🎂
