### ISSUE TITLE
Roadmap for v0.4.0

### ISSUE THREAD

**Issue by zimmski** [symflower/eval-dev-quality#35]
The v0.4.0 is mainly meant for introducing Java to the benchmark. There are two main goals
1. Simply to the same evaluation we did with 0.3.0 with plain.go, but this time with a plain.java.
2. Automate the interpretation of the evaluation result as much as possible so we can iterate on new releases faster (every release needs a blog post about the results)

Tasks:
- [x] Make assessments (and metrics) of tasks more generic and automated:
  - [x] Refactor metrics into a common assessment map #34 #33
  - [x] Move all metrics to be automatically interpreted:
    - [x] "Execute" #38
    - [x] "Problem" #38
    - [x] "Coverage" #38
    - [x] "Extra text" #33
    - [x] Automatic categorization of models #32 #39
  - [x] Models should have "points" so they can be compared and sorted
    - [x] Introduce score and sort #41
- [x] Generate .md with a automatically written report
  - [x] General generation of .md file with SVG #49
  - [x] Link models right away to correct file
    - [x] Update current blog post to bring in the directory of the repository for the evaluation results.
    - [x] Update current blog post to link to the evaluation files of the models
- [x] Test all the code we have, so from now on we only allow changes with tests
  - [x] Evaluation package #40
  - [x] Binary #46
- [x] Split results into separate files
  - [x] Split logs of models #25
  - [x] Use relative file paths in logs (not absolute, because absolute paths are hard to verify and compare by others)
- [x] Automatic tool installation with fixed version
  - [x] Symflower #47 #50
- [x] "plain.java" #61
- [x] Release
  - [x] Do a full evaluation with the new version
  - [x] Tag version
  - [x] Blog post
  - [x] Adapt README
  - [x] Announce and eat cake

**Comment by bauersimon** [comment]
Scoring, Categorization, Bar Charts split by language.

**Comment by zimmski** [comment]
Check determinism of models e.g. execute each plain repository X-times, and then check if they are stable.

**Comment by zimmski** [comment]
Save the descriptons of the models as well: https://openrouter.ai/api/v1/models

The reason is that these can change over time, and we need to know after a while what they where. e.g right now i would like to know if mistral-7b-instruct for the last evaluation was v0.1. or not

**Comment by zimmski** [comment]
Order models by open.weight, allows commercial-use, closed, and price(!) and size: e.g. https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1 is great because open-weight, and Apache2 so commerical-use allowed. Should be better rated than GPT4

**Comment by zimmski** [comment]
Write down a playbook for evaluations
- e.g. one thing that should happen is that we let the benchmark play 5 times and then sum up  points, but ... the runs should have at least one hour berak in between to not run into cached responses.

**Comment by zimmski** [comment]
Bar charts should have have their value on the bar. The axis values do not work that well

**Comment by zimmski** [comment]
Pick an example or several examples per category: goal is to find interesting results automatically, because it will get harder and harder to go manually through results.

**Comment by zimmski** [comment]
Do test file paths through
- `symflower symbols`
- Task for models

**Comment by zimmski** [comment]
Added all follow ups to https://github.com/symflower/eval-dev-quality/issues/79 so this issue is officially closed for changes. We only do the last tasks and then close it

CC @bauersimon

**Comment by zimmski** [comment]
Finally. Eating that cake!
